### ISSUE TITLE
Frequent Exception when connecting an Empatica

### ISSUE THREAD

**Issue by sboettcher** [RADAR-CNS/RADAR-Android-Empatica#4]
I have been getting these Exceptions sometimes, when connecting a new Empatica after disconnecting another. It seems to not happen every time, but when it does it is quite a nuisance since the app crashes.
```
59:40.165 2206-2348/org.radarcns.android.android E/AndroidRuntime: FATAL EXCEPTION: E4-device-handler
  Process: org.radarcns.android.android, PID: 2206
  java.lang.NullPointerException: Attempt to invoke virtual method 'android.bluetooth.BluetoothGattService android.bluetooth.BluetoothGatt.getService(java.util.UUID)' on a null object reference
    at com.empatica.empalink.EmpaLinkBLE.a(EmpaLinkBLE.java:284)
    at com.empatica.empalink.EmpaLinkBLE.c(EmpaLinkBLE.java:235)
    at com.empatica.empalink.EmpaDeviceManager.disconnect(EmpaDeviceManager.java:388)
    at org.radarcns.empatica.E4DeviceManager$4.run(E4DeviceManager.java:221)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.os.HandlerThread.run(HandlerThread.java:61)
07-28 17:59:40.167 1062-1693/? W/ActivityManager:   Force finishing activity org.radarcns.android.android/org.radarcns.DetailMainActivity
```

**Comment by sboettcher** [comment]
can not confirm that #5 fixes, I still just now got the exception when connecting an E4

**Comment by blootsvoets** [comment]
Ok, will just catch the exception then, it may be unavoidable.

**Comment by sboettcher** [comment]
I also earlier got a similar exception, however that was not with #5 in place. Will see if it returns again now
```
01-01 00:13:49.008 15220-18312/org.radarcns.android.android E/AndroidRuntime: FATAL EXCEPTION: E4-device-handler
  Process: org.radarcns.android.android, PID: 15220
  java.lang.NullPointerException: Attempt to invoke virtual method 'void com.empatica.empalink.EmpaLinkBLE.a()' on a null object reference
    at com.empatica.empalink.EmpaDeviceManager.startScanning(EmpaDeviceManager.java:325)
    at org.radarcns.empatica.E4DeviceManager$2.run(E4DeviceManager.java:123)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by blootsvoets** [comment]
That latest issue is now also addressed in #5 with 4070788.

**Comment by sboettcher** [comment]
Tested it in a dev setup, looks good so far! :D

**Comment by sboettcher** [comment]
#5 fixes.
