### ISSUE TITLE
App crashes on com.empatica.empalink.ConfigurationProfileException

### ISSUE THREAD

**Issue by fnobilia** [RADAR-CNS/RADAR-Android-Empatica#7]
Starting the Android app using `org.radarcns:radar-android-empatica:0.1-alpha.3` without internet connection raises 

```
01-01 00:08:04.044 3859-4152/org.radarcns.detail E/EMPA_C: Loaded
01-01 00:08:07.865 3859-4273/org.radarcns.detail E/DeviceLabelHandler: Error downloading label file
01-01 00:08:08.117 3859-3859/org.radarcns.detail E/AndroidRuntime: FATAL EXCEPTION: main
Process: org.radarcns.detail, PID: 3859
com.empatica.empalink.ConfigurationProfileException: Login failed and you don't have a valid local configuration profile
at com.empatica.empalink.EmpaDeviceManager.b(EmpaDeviceManager.java:843)
at com.empatica.empalink.EmpaDeviceManager.a(EmpaDeviceManager.java:67)
at com.empatica.empalink.EmpaDeviceManager$b.a(EmpaDeviceManager.java:1005)
at com.empatica.empalink.EmpaDeviceManager$b.onPostExecute(EmpaDeviceManager.java:978)
at android.os.AsyncTask.finish(AsyncTask.java:651)
at android.os.AsyncTask.-wrap1(AsyncTask.java)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

The Android app then crashes without recovering.

**Comment by sboettcher** [comment]
Yes that has always been the case, I have always solved it by starting the app with internet connection ;-). Could maybe be solved by catching the exception and periodically retrying?
Edit: this only needs to work once in the apps lifetime, i.e. until data is cleared or app is completely reinstalled
